### ISSUE TITLE
no possibility to log out 

### ISSUE THREAD

**Issue by wronka1007** [emeth-defi-automation/portfolio-management-platform#231]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/aleks/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/aleks/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Description | Steps | Expected Results | Current results
-- | -- | -- | --
Logout | 1) Log in | After clicking on the ‘logout’   button, the user is correctly logged out | After clicking on the ‘logout’   button, the user can't logged out

</body>

</html>

<img width="1276" alt="logout" src="https://github.com/emeth-defi-automation/portfolio-management-platform/assets/112552353/7c3cf867-d065-4f94-aebf-85e3381c0c4c">

**Comment by anhelinakruk** [comment]
I think it works now :) Can U check again pls? @wronka1007

**Comment by wronka1007** [comment]
When you log in to the app and click logout, a popup is displayed with the option to log out, when you click "logout", you are correctly logged out of the app. 
Test passed.
