### ISSUE TITLE
no wallet deletion popup

### ISSUE THREAD

**Issue by wronka1007** [emeth-defi-automation/portfolio-management-platform#232]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/aleks/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/aleks/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Description | Steps | Expected Results | Current results
-- | -- | -- | --
Delete   wallet | 1) Log in     2) Go through the process of setting up a portfolio if you don't have   one     3) Delete wallet | When a wallet is deleted, a   popup is displayed about the deletion of the wallet, the same as when adding   a wallet | no popup on success of wallet   removal

</body>

</html>

https://github.com/emeth-defi-automation/portfolio-management-platform/assets/112552353/ee15a42e-b3b1-410b-91ad-c78515ccb698

**Comment by anhelinakruk** [comment]
@wronka1007 
Can you please check it again? Someone must have fixed it, because as far as I can see, it's working correctly now :)

**Comment by wronka1007** [comment]
> @wronka1007 Can you please check it again? Someone must have fixed it, because as far as I can see, it's working correctly now :)

Yes, it is already working properly, test passed.
