### ISSUE TITLE
Content boxes don't have gray gradient fill

### ISSUE THREAD

**Issue by marcinlesek** [emeth-defi-automation/portfolio-management-platform#63]
All our content boxes (on `dashboard` or `wallets` pages) don't have gray gradient fill.

Actually:
![image](https://github.com/emeth-defi-automation/portfolio-management-platform/assets/13199192/1f5b4392-383e-4c4a-bd1c-1eb500455bf2)

[Figma](https://www.figma.com/file/QKK9ToOaCw3FBJ75416xqg/emeth?type=design&node-id=260-11759&mode=design&t=UqQ8hSsRwem6aZxf-0):
![image](https://github.com/emeth-defi-automation/portfolio-management-platform/assets/13199192/b309db08-95c4-4584-89f7-3d14fcf31432)

**Comment by Uacias** [comment]
The figma screenshot is old version

**Comment by marcinlesek** [comment]
@Uacias in new version Figma I still see this glass shade in boxes and in our version of application not (screen below, on left we have app, on right we have new Figma).

![image](https://github.com/emeth-defi-automation/portfolio-management-platform/assets/13199192/c53d8fb3-be19-4b78-ac0d-5a9fbc9867a9)

**Comment by anhelinakruk** [comment]
Done :)

**Comment by marcinlesek** [comment]
Confirming, thank you!
