### ISSUE TITLE
Action buttons are smaller

### ISSUE THREAD

**Issue by marcinlesek** [emeth-defi-automation/portfolio-management-platform#64]
All action buttons on `dashboard` page in content boxes are not properly aligned with the Figma design. They are thinner on top and bottom and a bit darker (Figma says 30% opacity).

Actually:
![image](https://github.com/emeth-defi-automation/portfolio-management-platform/assets/13199192/229aa241-03ae-425f-b24c-8664b206dcf8)

[Figma](https://www.figma.com/file/QKK9ToOaCw3FBJ75416xqg/emeth?type=design&node-id=260-11759&mode=design&t=UqQ8hSsRwem6aZxf-0):
![image](https://github.com/emeth-defi-automation/portfolio-management-platform/assets/13199192/ccb7bcbe-c045-4139-a121-1ed8f4f551a7)

**Comment by anhelinakruk** [comment]
Done :)

**Comment by marcinlesek** [comment]
Yop, confirms - it looks great now, thank you!
