### ISSUE TITLE
Portfolio default box border doesn't have a margin

### ISSUE THREAD

**Issue by marcinlesek** [emeth-defi-automation/portfolio-management-platform#65]
Portfolio default box border is going till the end of the web without any margin or space there (bottom part). Changing resolution doesn't help here.

Actual:
![image](https://github.com/emeth-defi-automation/portfolio-management-platform/assets/13199192/0e9223d4-07cd-4832-9a22-20f736196e51)

[Figma](https://www.figma.com/file/QKK9ToOaCw3FBJ75416xqg/emeth?type=design&node-id=548-17762&mode=design&t=UqQ8hSsRwem6aZxf-0):
![image](https://github.com/emeth-defi-automation/portfolio-management-platform/assets/13199192/aa01edd1-bfe4-4e09-8c1f-3b648d50c662)

**Comment by Uacias** [comment]
This one was fixed recently, staging did not include that change.

**Comment by marcinlesek** [comment]
✅
