### ISSUE TITLE
Adding new read only wallet cause ERROR 500

### ISSUE THREAD

**Issue by marcinlesek** [emeth-defi-automation/portfolio-management-platform#67]
1. Log in to app
2. Go to `wallets` page
3. Fill in all required information for read only mode wallet
4. See both success and error message modals at the same time

```
POST https://stg.emeth.xyz/app/wallets/?qfunc=2uTJYsS576w 500 (Internal Server Error)
```
```
["[C0006] Request failed, Not Found(404): Stream not found"]
```

![image11](https://github.com/emeth-defi-automation/portfolio-management-platform/assets/13199192/fbffc80d-8772-4151-af62-d8a457d00e39)

**Comment by furmanp** [comment]
cannot reproduce on current dev branch. Tried multiple times w/ different wallets.
