### ISSUE TITLE
Add the wallet form looks different than in design

### ISSUE THREAD

**Issue by marcinlesek** [emeth-defi-automation/portfolio-management-platform#68]
Add the wallet form looks different than in Figma design.

Actually:
![image](https://github.com/emeth-defi-automation/portfolio-management-platform/assets/13199192/0ba4eb36-762b-4c5b-bb00-2e614d5d578e)

[Figma](https://www.figma.com/file/QKK9ToOaCw3FBJ75416xqg/emeth?type=design&node-id=381-12253&mode=design&t=UqQ8hSsRwem6aZxf-0):
![image](https://github.com/emeth-defi-automation/portfolio-management-platform/assets/13199192/71165689-5545-46bb-b104-22e199d36ddc)

**Comment by Uacias** [comment]
Executable - Read-only switch will be changed, but turned out to be a bit problematic so we keep it 4 now,  the button is fixed, wallet address looks better, but there is still convert button so it doesn't look excatly like design in figma, we shall discuss this with the designer ig

**Comment by marcinlesek** [comment]
Yea, works for me - if we'll get approval of Designer, I'll be good here too. 😉
