### ISSUE TITLE
Dashboard layout is different

### ISSUE THREAD

**Issue by marcinlesek** [emeth-defi-automation/portfolio-management-platform#84]
1. Log in to app
2. Check out dashboard layout

In Figma, we have Portfolio Value, Alerts and Actions (6 elements in box) together in one row and Favourite Tokens in second row. Both this rows takes about 50/50 space.

![image](https://github.com/emeth-defi-automation/portfolio-management-platform/assets/13199192/fd0335e2-3654-4f85-9e2d-b1a492c426c2)

Actually, in our app, first row takes only 1/3 of the page space (Alerts and Actions now shows only 3 elements) and Favourite Tokens are on 2/3 of page space.

![image](https://github.com/emeth-defi-automation/portfolio-management-platform/assets/13199192/0ad0a34a-6aef-4d61-8667-044684f502a8)

**Comment by marcinlesek** [comment]
@anhelinakruk @DariaKozlovska we need to talk about it. 😉

**Comment by anhelinakruk** [comment]
Now Alerts and Action containers have 5 items each (as in Figma design). The height of Favourite Tokens row will depend on how much elements are in it. The whole page can be scrolled.

**Comment by marcinlesek** [comment]
Perfect, confirming it looks good! Closing issue.
